// <auto-generated />
namespace FARAHAT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class sasas333 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sasas333));
        
        string IMigrationMetadata.Id
        {
            get { return "202304012241460_sasas333"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
